### PR TITLE
initial conflux-abigen

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @boqiu and @wangdayong228)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1#-MfGw-FM1CL3O4lHSACQ:-MfGw-FN0TTuR5nG8mcm:b6cfcjz) ([raw file](https://github.com/conflux-chain/conflux-abigen/blob/15dfc905764058cb8276ef4b131735b24ab81ef6/README.md#L10)):*
> ```Markdown
> ### Install
> ```
> $ go install ./cmd/cfxabigen
> ```

can users install cfxabigen through a repo URL ?
___
*[example/keystore/UTC--2021-07-13T09-06-25.113259000Z--7502add5a4a14c85c525e30a850c58fa15325f8c, line 1 at r1](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1#-MfH3Ikj7OimEav6f1u2:-MfH3Ikj7OimEav6f1u3:b-8manjf) ([raw file](https://github.com/conflux-chain/conflux-abigen/blob/15dfc905764058cb8276ef4b131735b24ab81ef6/example/keystore/UTC--2021-07-13T09-06-25.113259000Z--7502add5a4a14c85c525e30a850c58fa15325f8c#L1)):*
> ```
> {"address":"7502add5a4a14c85c525e30a850c58fa15325f8c","crypto":{"cipher":"aes-128-ctr","ciphertext":"f33267052a70dc2c8ec19d5cfc6b967e0dc4fe57303e67d5ee68a1f2eb669f4c","cipherparams":{"iv":"22caeaba10212ef1f68ff3bee6133f40"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"7a033315d3b6e0eb2089fbf533459a74af51e5b19dbedef7c5e850631e8f6d36"},"mac":"a11c4d12a475c2fd5ad314ecb5fdc8b2ccf888a3484f7972cf632b997f78faee"},"id":"9e8861ae-522e-4d6b-826f-a8cebe178d8d","version":3}
> ```

Better remove this file from repo

**Review by Pana — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1)* status: all files reviewed, 2 unresolved discussions (waiting on @boqiu and @wangdayong228)

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @boqiu and @Pana)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1#-MfGw-FM1CL3O4lHSACQ:-MfHBN-G4Y4WCMwYKE5g:b-896fix) ([raw file](https://github.com/conflux-chain/conflux-abigen/blob/15dfc905764058cb8276ef4b131735b24ab81ef6/README.md#L10)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

can users install cfxabigen through a repo URL ?
</blockquote></details>

Done.
___
*[example/keystore/UTC--2021-07-13T09-06-25.113259000Z--7502add5a4a14c85c525e30a850c58fa15325f8c, line 1 at r1](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1#-MfH3Ikj7OimEav6f1u2:-MfHBMQH10IY-dNlp49c:b-896fix) ([raw file](https://github.com/conflux-chain/conflux-abigen/blob/15dfc905764058cb8276ef4b131735b24ab81ef6/example/keystore/UTC--2021-07-13T09-06-25.113259000Z--7502add5a4a14c85c525e30a850c58fa15325f8c#L1)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Better remove this file from repo
</blockquote></details>

Done.

**Review by Pana — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-abigen/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)

**Pull request merged**
